[platformio]
default_envs = esp32-c6-supermini

[env:esp32-c6-supermini]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.312-1/platform-espressif32.zip
board = esp32-c6-devkitm-1
framework = arduino
board_build.partitions = huge_app.csv
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_BT_NIMBLE_ROLE_CENTRAL=1
    -DCONFIG_BT_NIMBLE_ROLE_OBSERVER=1
    -DBUTTON_PIN=9
upload_port = /dev/cu.usbmodem3101
upload_speed = 921600
monitor_port = /dev/cu.usbmodem3101
monitor_speed = 115200
lib_deps = 
    h2zero/NimBLE-Arduino @ ^2.1.0
    bblanchon/ArduinoJson @ ^7.0.4

[env:esp32-s3-supermini]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.partitions = huge_app.csv
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_BT_NIMBLE_ROLE_CENTRAL=1
    -DCONFIG_BT_NIMBLE_ROLE_OBSERVER=1
    -DBUTTON_PIN=0
upload_port = /dev/cu.usbmodem3101
upload_speed = 921600
monitor_port = /dev/cu.usbmodem3101
monitor_speed = 115200
lib_deps = 
    h2zero/NimBLE-Arduino @ ^2.1.0
    bblanchon/ArduinoJson @ ^7.0.4
